language: python

python:
    - 3.5
    - 3.6

install:
  - pip install coveralls
  - pip install git+https://github.com/benureau/leabra.git@master
  - pip install -e .[dev]

os:
  - linux

matrix:
  include:
  - os: osx
    python: 3.5
    language: generic
    env:
        - PYTHON=3.5.4
        - PYTHON_PKG_VERSION=macosx10.6
  - os: osx
    python: 3.6
    language: generic
    env:
        - PYTHON=3.6.5
        - PYTHON_PKG_VERSION=macosx10.9

addons:
  apt:
    packages:
      - graphviz

before_install: |
  if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    FILE=python-$PYTHON-$PYTHON_PKG_VERSION.pkg
    curl -O -#  https://www.python.org/ftp/python/$PYTHON/$FILE
    sudo installer -pkg $FILE -target /
    python3 --version
    # This sidesteps TLSv1.1 issue when using pip
    curl https://bootstrap.pypa.io/get-pip.py | python3
    python3 -m pip  install virtualenv
    python3 -m venv venv
    source venv/bin/activate
    python --version
    # virtualenv installs default pip even if we updated it above.
    # update it again.
    curl https://bootstrap.pypa.io/get-pip.py | python

    # setuptools also face the same TLS deprecation issue.
    # Update them explicitly
    python -m pip install -U setuptools
    python -m pip install -U setuptools-git

    HOMEBREW_NO_AUTO_UPDATE=1 brew install graphviz
  fi

script:
  - python -m pytest -p no:logging --cov=psyneulink tests/

after_script:
  - coveralls
