language: python

python:
    - 3.5
    - 3.6

sudo: false

install:
  - pip install coveralls
  - pip install git+https://github.com/benureau/leabra.git@master
  - pip install -e .[dev]

os:
  - linux

# Cache installed python packages
cache:
  directories:
    - $HOME/virtualenv/python${TRAVIS_PYTHON_VERSION}/lib/python${TRAVIS_PYTHON_VERSION}/site-packages
    - $HOME/virtualenv/python${TRAVIS_PYTHON_VERSION}/bin

matrix:
  include:
  - python: 3.7
    dist: xenial # Python 3.7 is only available on xenial because of deps
    sudo: required

  - os: osx
    python: 3.5
    language: generic
    env:
        - PYTHON=3.5.4
        - PYTHON_PKG_VERSION=macosx10.6
        - PRIV=sudo
    # Cache installed python virtual env and homebrew downloads
    cache:
        directories:
          - $HOME/venv
          - $HOME/Library/Caches/Homebrew

  - os: osx
    python: 3.6
    language: generic
    env:
        - PYTHON=3.6.7
        - PYTHON_PKG_VERSION=macosx10.9
        - PRIV=sudo
    # Cache installed python virtual env and homebrew downloads
    cache:
        directories:
          - $HOME/venv
          - $HOME/Library/Caches/Homebrew

  - os: osx
    python: 3.7
    language: generic
    env:
        - PYTHON=3.7.1
        - PYTHON_PKG_VERSION=macosx10.9
        - PRIV=sudo
    # Cache installed python virtual env and homebrew downloads
    cache:
        directories:
          - $HOME/venv
          - $HOME/Library/Caches/Homebrew

addons:
  apt:
    packages:
      - graphviz

before_install: |
  if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    FILE=python-$PYTHON-$PYTHON_PKG_VERSION.pkg
    curl -O -#  https://www.python.org/ftp/python/$PYTHON/$FILE
    $PRIV installer -pkg $FILE -target /
    python3 --version
    # Check if the cached version is available
    if [ "x`$HOME/venv/bin/python --version`" == "xPython $PYTHON" ] ; then
       echo "Reusing python venv"
       source $HOME/venv/bin/activate
       python --version
    else
       echo "Deploying new python venv"
       # This sidesteps TLSv1.1 issue when using pip
       curl https://bootstrap.pypa.io/get-pip.py | python3
       python3 -m pip  install virtualenv
       python3 -m venv $HOME/venv
       source $HOME/venv/bin/activate
       python --version
       # virtualenv installs default pip even if we updated it above.
       # update it again.
       curl https://bootstrap.pypa.io/get-pip.py | python

       # setuptools also face the same TLS deprecation issue.
       # Update them explicitly
       python -m pip install -U setuptools
       python -m pip install -U setuptools-git
    fi

    HOMEBREW_NO_AUTO_UPDATE=1 brew install graphviz
  fi

script:
  - python -m pytest -p no:logging --cov=psyneulink tests/

after_script:
  - coveralls
